services:
  srv1:
    image: my-bench-server:latest
    build: 
      context: .
      dockerfile: src/Dockerfile.Server
    networks:
      - MasterLab
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    environment:
      - ID=1
      - SERVER=1
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - LOG=${LOG}
    volumes:
      - /home/ubuntu/gorums-benchmark/logs:/app/logs
    deploy:
      placement:
        constraints: [node.hostname == node-1]

  srv2:
    image: my-bench-server:latest
    build: 
      context: .
      dockerfile: src/Dockerfile.Server
    networks:
      - MasterLab
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    environment:
      - ID=2
      - SERVER=1
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - LOG=${LOG}
    volumes:
      - /home/ubuntu/gorums-benchmark/logs:/app/logs
    deploy:
      placement:
        constraints: [node.hostname == node-2]

  srv3:
    image: my-bench-server:latest
    build: 
      context: .
      dockerfile: src/Dockerfile.Server
    networks:
      - MasterLab
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    environment:
      - ID=3
      - SERVER=1
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - LOG=${LOG}
    volumes:
      - /home/ubuntu/gorums-benchmark/logs:/app/logs
    deploy:
      placement:
        constraints: [node.hostname == node-3]

  srv4:
    image: my-bench-server:latest
    build: 
      context: .
      dockerfile: src/Dockerfile.Server
    networks:
      - MasterLab
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    environment:
      - ID=4
      - SERVER=1
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - LOG=${LOG}
    volumes:
      - /home/ubuntu/gorums-benchmark/logs:/app/logs
    deploy:
      placement:
        constraints: [node.hostname == node-4]

  client:
    image: my-bench-client:latest
    build: 
      context: .
      dockerfile: src/Dockerfile.Client
    networks:
      - MasterLab
    environment:
      - SERVER=0
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - THROUGHPUT=${THROUGHPUT}
      - STEPS=${STEPS}
      - RUNS=${RUNS}
      - DUR=${DUR}
      - LOG=${LOG}
    volumes:
      - /home/ubuntu/gorums-benchmark/logs:/app/logs
      - /home/ubuntu/gorums-benchmark/csv:/app/src/csv
    deploy:
      placement:
        constraints: [node.hostname == node-1]

networks:
  MasterLab:
    external: true
